### ISSUE TITLE
Latest x265 uses API version 173

### ISSUE THREAD

**Issue by dprestegard** [DolbyLaboratories/dolby-encoding-engine#3]
Looks like something recently added to the master x265 branch (certainly asof https://bitbucket.org/multicoreware/x265/commits/feec4bdf98663ac4a2561b63e1ccec423c7d26a4)

has upped the API version to 173, which breaks building the x265 plugin for DEE.

Visual Studio complains:

1>------ Rebuild All started: Project: hevc_enc_x265, Configuration: release x64 ------
1>  hevc_enc_x265.cpp
1>..\..\..\src\hevc_enc_x265.cpp(474): warning C4456: declaration of 'nal' hides previous local declaration
1>  ..\..\..\src\hevc_enc_x265.cpp(380): note: see declaration of 'nal'
1>..\..\..\src\hevc_enc_x265.cpp(537): warning C4456: declaration of 'nal' hides previous local declaration
1>  ..\..\..\src\hevc_enc_x265.cpp(505): note: see declaration of 'nal'
1>  hevc_enc_x265_utils.cpp
1>..\..\..\src\hevc_enc_x265_utils.cpp(823): warning C4456: declaration of 'i' hides previous local declaration
1>  ..\..\..\src\hevc_enc_x265_utils.cpp(234): note: see declaration of 'i'
1>     Creating library F:\DEE Building\dolby-encoding-engine-3.0\dolby-encoding-engine\plugins\code\hevc_enc\x265\make\hevc_enc_x265\windows_amd64_msvs\release\VS2013\hevc_enc_x265.lib and object F:\DEE Building\dolby-encoding-engine-3.0\dolby-encoding-engine\plugins\code\hevc_enc\x265\make\hevc_enc_x265\windows_amd64_msvs\release\VS2013\hevc_enc_x265.exp
1>hevc_enc_x265.obj : error LNK2001: unresolved external symbol x265_api_get_173
1>F:\DEE Building\dolby-encoding-engine-3.0\dolby-encoding-engine\plugins\code\hevc_enc\x265\make\hevc_enc_x265\windows_amd64_msvs\release\VS2013\hevc_enc_x265.dll : fatal error LNK1120: 1 unresolved externals
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by marog** [comment]
Hello Derek,

I'm able to reproduce this when the directory indicated by $X265ROOT has been updated with the newly compiled libx265.lib libx265.dll, but the include directory was not updated with the new x265.h and x265_config.h, so syncing them up should do the job.

Regards,
Marek
