### ISSUE TITLE
NAL_UNIT_CODED_SLICE_TLA_R not declared.

### ISSUE THREAD

**Issue by sleepfrontofmtv** [DolbyLaboratories/dolby-encoding-engine#4]
It appears that NAL_UNIT_CODED_SLICE_TLA_R has been modified from the x265 source, which makes an error when compiling.
https://bitbucket.org/multicoreware/x265_git/src/8f18e3ad32684eee95e885e718655f93951128c3/source/x265.h#lines-63
https://bitbucket.org/multicoreware/x265_git/commits/4d0edcc2161cfead12e3c265e050d3162ccb4bf6/raw

So it seems need to modify hevc_enc_x265_utils.cpp, line 930
https://github.com/DolbyLaboratories/dolby-encoding-engine/blob/c2e53ae48b23357e3fd7d0a0840f27fb1e80aba4/plugins/code/hevc_enc/x265/src/hevc_enc_x265_utils.cpp#L930

It can still be compiled "hevc_enc_x265.dll" by modifying # 930.

1. > TLA_R to TSA_R in type

```c++
else if (type == NAL_UNIT_CODED_SLICE_TSA_R) out = HEVC_ENC_NAL_UNIT_CODED_SLICE_TLA_R;
```
2. > or remove this line.

Is it ok to change this line? or do you plan an update for it?

**Comment by mszym1** [comment]
Thank you for reporting this.
Seem like in our internal tests we rely on x265 version that still had this enum.
It's fine to remove this line. As a result, the slice would be reported to the DEE framework as HEVC_ENC_NAL_UNIT_OTHER, which shouldn't cause any harm.

**Comment by sleepfrontofmtv** [comment]
Thank you for letting me know!
